# Generated by Django 5.2.7 on 2025-11-21 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('OTHER', '......'), ('OFFICER', 'Offr'), ('DAD', 'DAD'), ('SI', 'SI'), ('ASI', 'ASI'), ('NAYEK', 'Nek'), ('CONSTABLE', 'Con'), ('CIVIL', 'Civ')], max_length=20)),
                ('force', models.CharField(choices=[('OTHER', '......'), ('ARMY', 'Army'), ('NAVY', 'Navy'), ('AIR', 'Air'), ('POLICE', 'Police'), ('BGB', 'BGB'), ('VDP', 'Ansar VDP'), ('CIV', 'Civ')], max_length=20)),
                ('company', models.CharField(choices=[('OTHER', '......'), ('cpc-1', 'CPC-1'), ('cpc-2', 'CPC-2'), ('cpc-3', 'CPC-3'), ('cpsc', 'CPSC'), ('hq', 'HQ'), ('Bn HQ', 'Bn HQ'), ('ro', 'RO'), ('mi', 'Mi'), ('ab', 'A Branch')], max_length=50)),
                ('svc_join', models.DateField()),
                ('rab_join', models.DateField()),
                ('birth_day', models.DateField()),
                ('nid', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('wf_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='tasks.forcemember')),
            ],
        ),
        migrations.CreateModel(
            name='AcctBr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acctbr', to='tasks.forcemember')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.forcemember')),
            ],
        ),
        migrations.CreateModel(
            name='MiRoomVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('treatment', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_visits', to='tasks.forcemember')),
            ],
        ),
        migrations.CreateModel(
            name='Mt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt', to='tasks.forcemember')),
            ],
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=20)),
                ('road', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=20)),
                ('thana', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=30)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='tasks.forcemember')),
            ],
        ),
        migrations.CreateModel(
            name='PresentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=20)),
                ('road', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=20)),
                ('thana', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=30)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='present_address', to='tasks.forcemember')),
            ],
        ),
        migrations.CreateModel(
            name='Ro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ro', to='tasks.forcemember')),
            ],
        ),
        migrations.CreateModel(
            name='TrgBr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rab_id', models.IntegerField(unique=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trg', to='tasks.forcemember')),
            ],
        ),
    ]
