# Generated by Django 5.2.7 on 2025-11-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcemember',
            name='company',
            field=models.CharField(blank=True, choices=[('OTHER', '......'), ('cpc-1', 'CPC-1'), ('cpc-2', 'CPC-2'), ('cpc-3', 'CPC-3'), ('cpsc', 'CPSC'), ('hq', 'HQ'), ('Bn HQ', 'Bn HQ'), ('ro', 'RO'), ('mi', 'Mi'), ('ab', 'A Branch')], max_length=50, null=True),
        ),
    ]
