# Generated by Django 5.2.7 on 2025-11-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_forcemember_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentaddress',
            name='post',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='presentaddress',
            name='post',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
