# Generated by Django 5.2.7 on 2025-11-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_permanentaddress_post_presentaddress_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcemember',
            name='mother_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
